# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AwesomeWebview' do

end

target 'AwesomeWebviewTests' do

end

pod 'powerdefines'
pod 'MBProgressHUD', '~> 0.9.1'